version: 2.1

workflows:
  version: 2
  validate-opa-dockerfile-benchmark:
    jobs:
      - perform-test

jobs:
  perform-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install bats and conftest
          command: |
            whoami
            pwd
            bash install_requirements.sh
            bats -v
            conftest --version
      - run:
          name: run tests
          working_directory: test
          command: |
            conftest test -i Dockerfile Dockerfile.level2 --data .opacisrc.level2 -p ../policy
            #bats test-benchmark.bats
