version: 2.1

workflows:
  version: 2
  validate-opa-dockerfile-benchmark:
    jobs:
      - perform-test

jobs:
  perform-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install bats and conftest
          command: |
            npm install --save-dev bats
            npm install --save-dev https://github.com/ztombol/bats-support
            npm install --save-dev https://github.com/ztombol/bats-assert
            bats -v
            wget https://github.com/instrumenta/conftest/releases/download/v0.17.1/conftest_0.17.1_Linux_x86_64.tar.gz
            tar xzf conftest_0.17.1_Linux_x86_64.tar.gz
            sudo mv conftest /usr/local/bin
            conftest --version
      - run:
          name: run tests
          working_directory: test
          command: |
            bats test-benchmark.bats
